In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor


from sklearn.metrics import mean_squared_error

In [6]:
#read your csv files here
day = pd.read_csv('day.csv')
hour =pd.read_csv('hour.csv')

In [10]:
#Checking for Missing Values in Day Dataset
day.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [12]:
#Checking for Missing Values in Hour Dataset
hour.isna().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [19]:
#Check the count, mean and other statistical features in your dataset (use describe)
day.describe()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
count,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
mean,366.000000,2.496580,0.500684,6.519836,0.028728,2.997264,0.683995,1.395349,0.495385,0.474354,0.627894,0.190486,848.176471,3656.172367,4504.348837
std,211.165812,1.110807,0.500342,3.451913,0.167155,2.004787,0.465233,0.544894,0.183051,0.162961,0.142429,0.077498,686.622488,1560.256377,1937.211452
min,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.059130,0.079070,0.000000,0.022392,2.000000,20.000000,22.000000
25%,183.500000,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,0.337083,0.337842,0.520000,0.134950,315.500000,2497.000000,3152.000000
50%,366.000000,3.000000,1.000000,7.000000,0.000000,3.000000,1.000000,1.000000,0.498333,0.486733,0.626667,0.180975,713.000000,3662.000000,4548.000000
75%,548.500000,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,0.655417,0.608602,0.730209,0.233214,1096.000000,4776.500000,5956.000000
max,731.000000,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,0.861667,0.840896,0.972500,0.507463,3410.000000,6946.000000,8714.000000

In [20]:
#check the correlation between different columns of your dataset (use df.corr())
day.corr()

,instant,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
instant,1.000000,0.412224,0.866025,0.496702,0.016145,-0.000016,-0.004337,-0.021477,0.150580,0.152638,0.016375,-0.112620,0.275255,0.659623,0.628830
season,0.412224,1.000000,-0.001844,0.831440,-0.010537,-0.003080,0.012485,0.019211,0.334315,0.342876,0.205445,-0.229046,0.210399,0.411623,0.406100
yr,0.866025,-0.001844,1.000000,-0.001792,0.007954,-0.005461,-0.002013,-0.048727,0.047604,0.046106,-0.110651,-0.011817,0.248546,0.594248,0.566710
mnth,0.496702,0.831440,-0.001792,1.000000,0.019191,0.009509,-0.005901,0.043528,0.220205,0.227459,0.222204,-0.207502,0.123006,0.293488,0.279977
holiday,0.016145,-0.010537,0.007954,0.019191,1.000000,-0.101960,-0.253023,-0.034627,-0.028556,-0.032507,-0.015937,0.006292,0.054274,-0.108745,-0.068348
weekday,-0.000016,-0.003080,-0.005461,0.009509,-0.101960,1.000000,0.035790,0.031087,-0.000170,-0.007537,-0.052232,0.014282,0.059923,0.057367,0.067443
workingday,-0.004337,0.012485,-0.002013,-0.005901,-0.253023,0.035790,1.000000,0.061200,0.052660,0.052182,0.024327,-0.018796,-0.518044,0.303907,0.061156
weathersit,-0.021477,0.019211,-0.048727,0.043528,-0.034627,0.031087,0.061200,1.000000,-0.120602,-0.121583,0.591045,0.039511,-0.247353,-0.260388,-0.297391
temp,0.150580,0.334315,0.047604,0.220205,-0.028556,-0.000170,0.052660,-0.120602,1.000000,0.991702,0.126963,-0.157944,0.543285,0.540012,0.627494
atemp,0.152638,0.342876,0.046106,0.227459,-0.032507,-0.007537,0.052182,-0.121583,0.991702,1.000000,0.139988,-0.183643,0.543864,0.544192,0.631066
hum,0.016375,0.205445,-0.110651,0.222204,-0.015937,-0.052232,0.024327,0.591045,0.126963,0.139988,1.000000,-0.248489,-0.077008,-0.091089,-0.100659
windspeed,-0.112620,-0.229046,-0.011817,-0.207502,0.006292,0.014282,-0.018796,0.039511,-0.157944,-0.183643,-0.248489,1.000000,-0.167613,-0.217449,-0.234545
casual,0.275255,0.210399,0.248546,0.123006,0.054274,0.059923,-0.518044,-0.247353,0.543285,0.543864,-0.077008,-0.167613,1.000000,0.395282,0.672804
registered,0.659623,0.411623,0.594248,0.293488,-0.108745,0.057367,0.303907,-0.260388,0.540012,0.544192,-0.091089,-0.217449,0.395282,1.000000,0.945517
cnt,0.628830,0.406100,0.566710,0.279977,-0.068348,0.067443,0.061156,-0.297391,0.627494,0.631066,-0.100659,-0.234545,0.672804,0.945517,1.000000

In [21]:
#look at your data (use head())
day.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,2011-01-01,1,0,1,0,6,0,2,0.344167,0.363625,0.805833,0.160446,331,654,985
1,2,2011-01-02,1,0,1,0,0,0,2,0.363478,0.353739,0.696087,0.248539,131,670,801
2,3,2011-01-03,1,0,1,0,1,1,1,0.196364,0.189405,0.437273,0.248309,120,1229,1349
3,4,2011-01-04,1,0,1,0,2,1,1,0.200000,0.212122,0.590435,0.160296,108,1454,1562
4,5,2011-01-05,1,0,1,0,3,1,1,0.226957,0.229270,0.436957,0.186900,82,1518,1600

In [22]:
#check column names in Day dataset
day.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

In [23]:
#check column names in Hour dataset
hour.columns

Index(['instant', 'dteday', 'season', 'yr', 'mnth', 'hr', 'holiday', 'weekday',
       'workingday', 'weathersit', 'temp', 'atemp', 'hum', 'windspeed',
       'casual', 'registered', 'cnt'],
      dtype='object')

## Hour Dataset

### Q1(a) number of casual riders

In [27]:
#separating predictors and target columns: target here is 'casual' column
#drop columns ['casual', 'registered', 'cnt','dteday','instant'] from X
X = hour.drop(columns=['casual', 'registered', 'cnt', 'dteday', 'instant'])
y = hour[['casual']]

   season  yr  mnth  hr  holiday  weekday  workingday  weathersit  temp  \
0       1   0     1   0        0        6           0           1  0.24
1       1   0     1   1        0        6           0           1  0.22
2       1   0     1   2        0        6           0           1  0.22
3       1   0     1   3        0        6           0           1  0.24
4       1   0     1   4        0        6           0           1  0.24

    atemp   hum  windspeed
0  0.2879  0.81        0.0
1  0.2727  0.80        0.0
2  0.2727  0.80        0.0
3  0.2879  0.75        0.0
4  0.2879  0.75        0.0

In [29]:
#print the shape of X and y
print(X.shape)
print(y.shape)

(17379, 12)
(17379, 1)

In [31]:
#do a train test split, use test_size =0.3

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)



print("Linear Regression")
#initialize your linear regression model
lr = LinearRegression()
#fit training set to your LR model
lr = lr.fit(X_train, y_train)
#predict on the test set using your model
y_pred = lr.predict(X_test)
#evaluate: use MSE
print("MSE for LR: %.2f" %mean_squared_error(y_test,y_pred))




print("KNN")
#initialize your KNearestNeighbors model
knn = KNeighborsRegressor()
#fit training set to your KNN model
knn = knn.fit(X_train, y_train)
#predict on the test set using your model
y_pred = knn.predict(X_test)
#evaluate: use MSE
print("MSE for KNN: %.2f" %mean_squared_error(y_test,y_pred))

Linear Regression
MSE for LR: 1324.81
KNN
MSE for KNN: 342.98

### Q1(b) number of registered riders

In [32]:
#separating predictors and target columns : target here is 'registered' column
#drop columns ['casual', 'registered', 'cnt','dteday','instant'] from X
X = hour.drop(columns=['casual', 'registered', 'cnt', 'dteday', 'instant'])
y = hour[['registered']]

In [33]:
#print the shape of X and y
print(X.shape, y.shape)

(17379, 12) (17379, 1)

In [35]:
#do a train test split, use test_size =0.3

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

print("Linear Regression")
#initialize your linear regression model
lr = LinearRegression()
#fit training set to your LR model
lr = lr.fit(X_train, y_train)
#predict on the test set using your model
y_pred = lr.predict(X_test)
#evaluate: use MSE
print("MSE for LR: %.2f" %mean_squared_error(y_test,y_pred))




print("KNN")
#initialize your KNearestNeighbors model
knn = KNeighborsRegressor()
#fit training set to your KNN model
knn = knn.fit(X_train, y_train)
#predict on the test set using your model
y_pred = knn.predict(X_test)
#evaluate: use MSE
print("MSE for KNN: %.2f" %mean_squared_error(y_test,y_pred))

Linear Regression
MSE for LR: 16008.37
KNN
MSE for KNN: 2259.16

### Q1(c) total ridership count

In [37]:
#separating predictors and target columns : target here is 'cnt' column
#drop columns ['casual', 'registered', 'cnt','dteday','instant'] from X
X = hour.drop(columns=['casual', 'registered', 'cnt', 'dteday', 'instant'])
y = hour[['cnt']]

In [38]:
#print the shape of X and y
print(X.shape, y.shape)

(17379, 12) (17379, 1)

In [39]:
#do a train test split, use test_size =0.3

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

print("Linear Regression")
#initialize your linear regression model
lr = LinearRegression()
#fit training set to your LR model
lr = lr.fit(X_train, y_train)
#predict on the test set using your model
y_pred = lr.predict(X_test)
#evaluate: use MSE
print("MSE for LR: %.2f" %mean_squared_error(y_test,y_pred))




print("KNN")
#initialize your KNearestNeighbors model
knn = KNeighborsRegressor()
#fit training set to your KNN model
knn = knn.fit(X_train, y_train)
#predict on the test set using your model
y_pred = knn.predict(X_test)
#evaluate: use MSE
print("MSE for KNN: %.2f" %mean_squared_error(y_test,y_pred))

Linear Regression
MSE for LR: 20863.80
KNN
MSE for KNN: 3138.65

## Day Dataset

### Q2(a) number of casual riders

In [43]:
#separating predictors and target columns : target here is 'casual' column
#drop columns ['casual', 'registered', 'cnt','dteday','instant'] from X
X = day.drop(columns=['casual', 'registered', 'cnt','dteday','instant'])
y = day[['casual']]

In [44]:
#print the shape of X and y
print(X.shape, y.shape)

(731, 11) (731, 1)

In [45]:
#do a train test split, use test_size =0.3

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

print("Linear Regression")
#initialize your linear regression model
lr = LinearRegression()
#fit training set to your LR model
lr = lr.fit(X_train, y_train)
#predict on the test set using your model
y_pred = lr.predict(X_test)
#evaluate: use MSE
print("MSE for LR: %.2f" %mean_squared_error(y_test,y_pred))




print("KNN")
#initialize your KNearestNeighbors model
knn = KNeighborsRegressor()
#fit training set to your KNN model
knn = knn.fit(X_train, y_train)
#predict on the test set using your model
y_pred = knn.predict(X_test)
#evaluate: use MSE
print("MSE for KNN: %.2f" %mean_squared_error(y_test,y_pred))

Linear Regression
MSE for LR: 146092.28
KNN
MSE for KNN: 119582.42

### Q2(b) number of registered riders

In [46]:
#separating predictors and target columns : target here is 'registered' column
#drop columns ['casual', 'registered', 'cnt','dteday','instant'] from X
X = day.drop(columns=['casual', 'registered', 'cnt','dteday','instant'])
y = day[['registered']]

In [47]:
#print the shape of X and y
print(X.shape, y.shape)

(731, 11) (731, 1)

In [48]:
#do a train test split, use test_size =0.3

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

print("Linear Regression")
#initialize your linear regression model
lr = LinearRegression()
#fit training set to your LR model
lr = lr.fit(X_train, y_train)
#predict on the test set using your model
y_pred = lr.predict(X_test)
#evaluate: use MSE
print("MSE for LR: %.2f" %mean_squared_error(y_test,y_pred))




print("KNN")
#initialize your KNearestNeighbors model
knn = KNeighborsRegressor()
#fit training set to your KNN model
knn = knn.fit(X_train, y_train)
#predict on the test set using your model
y_pred = knn.predict(X_test)
#evaluate: use MSE
print("MSE for KNN: %.2f" %mean_squared_error(y_test,y_pred))

Linear Regression
MSE for LR: 491173.88
KNN
MSE for KNN: 640425.74

### Q2(c) total ridership count

In [49]:
#separating predictors and target columns : target here is 'cnt' column
#drop columns ['casual', 'registered', 'cnt','dteday','instant'] from X
X = day.drop(columns=['casual', 'registered', 'cnt','dteday','instant'])
y = day[['cnt']]

In [50]:
#print the shape of X and y
print(X.shape, y.shape)

(731, 11) (731, 1)

In [51]:
#do a train test split, use test_size =0.3

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

print("Linear Regression")
#initialize your linear regression model
lr = LinearRegression()
#fit training set to your LR model
lr = lr.fit(X_train, y_train)
#predict on the test set using your model
y_pred = lr.predict(X_test)
#evaluate: use MSE
print("MSE for LR: %.2f" %mean_squared_error(y_test,y_pred))




print("KNN")
#initialize your KNearestNeighbors model
knn = KNeighborsRegressor()
#fit training set to your KNN model
knn = knn.fit(X_train, y_train)
#predict on the test set using your model
y_pred = knn.predict(X_test)
#evaluate: use MSE
print("MSE for KNN: %.2f" %mean_squared_error(y_test,y_pred))

Linear Regression
MSE for LR: 797103.77
KNN
MSE for KNN: 1058498.89